# This is a basic workflow to help you get started with Actions
- name: Azure Static Website
  # You may pin to the exact commit or the version.
  # uses: tibor19/static-website-deploy@e937952c714a3751355a17896498418a9931ded5
  uses: tibor19/static-website-deploy@v1
  with:
    # Connection String of the Azure Storage Container
    connection-string: https://devstaticqrstorage.blob.core.windows.net/$web
    # Folder containing the files to be uploaded to the Storage Container
    folder: # optional, default is .
    # Name of the Blob Container Storage
    blob-container-name: # optional
    # Access Policy to update in the Container (BlobContainer | Blob | None). For private containers do not specity any value.
    public-access-policy: # optional
    # Enabled static website
    enabled-static-website: # optional
    # Index file for the static website
    index-file: # optional
    # 404 Error file for the static website
    error-file: # optional
    # If the existing files should be removed before uploading the new files
    remove-existing-files: # optional
